# Generated by Django 6.0.1 on 2026-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resort',
            old_name='latitude',
            new_name='base_lat',
        ),
        migrations.RemoveField(
            model_name='resort',
            name='longitude',
        ),
        migrations.AddField(
            model_name='resort',
            name='base_lon',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resort',
            name='top_lat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resort',
            name='top_lon',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
