# Generated by Django 6.0.1 on 2026-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_rename_latitude_resort_base_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('top_elevation', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('region', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
