# Generated by Django 6.0.1 on 2026-07-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0004_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='description',
            new_name='weather_info',
        ),
        migrations.AddField(
            model_name='route',
            name='location',
            field=models.CharField(choices=[('Val dAran', 'Val dAran'), ('Pallars', 'Pallars'), ('Alta Ribagorça', 'Alta Ribagorça'), ('Cerdanya', 'Cerdanya'), ('Ripollés', 'Ripollés'), ('Pirineus', 'Pirineus')], default='Pirineus', max_length=64),
        ),
    ]
