# Generated by Django 6.0.1 on 2026-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0005_rename_description_route_weather_info_route_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='weather_info',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
