# Generated by Django 6.0.1 on 2026-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0006_alter_route_date_completed_alter_route_weather_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
