# Generated by Django 6.0.1 on 2026-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0007_alter_route_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
